kind: ApplicationSet
apiVersion: argoproj.io/v1alpha1
metadata:
  name: grafana
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster     
  template: 
    metadata:
      name: 'cluster-{{name}}-grafana'
      annotations:
        argocd.argoproj.io/sync-wave: "1"
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      project: "default"
      sources:
      - chart: grafana
        repoURL: https://grafana.github.io/helm-charts
        targetRevision: 8.4.1
        helm:
          releaseName: grafana
          valueFiles:
          - $values/helm-values/grafana-values.yaml
          valuesObject:
             kyverno.fullname: grafana
      - repoURL: https://github.com/sam0787/demo-namespaces-as-a-service.git
        targetRevision: feature/resource-optimiser
        ref: values
      destination:
        server: '{{server}}'
        namespace: monitoring
      syncPolicy:
        syncOptions:
        - Replace=true
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
        retry:
          limit: 30
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s