kind: ApplicationSet
apiVersion: argoproj.io/v1alpha1
metadata:
  name: kube-state-metrics
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster     
  template: 
    metadata:
      name: 'cluster-{{name}}-kube-state-metrics'
      annotations:
        argocd.argoproj.io/sync-wave: "1"
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      project: "default"
      sources:
      - chart: kube-state-metrics
        repoURL: https://prometheus-community.github.io/helm-charts
        targetRevision: 5.25.1
        helm:
          releaseName: kube-state-metrics
          valuesObject:
             kyverno.fullname: kube-state-metrics
          valueFiles:
          - $values/helm-values/kube-state-metric-values.yaml
      - repoURL: https://github.com/sam0787/demo-namespaces-as-a-service.git
        targetRevision: feature/resource-optimiser
        ref: values
      destination:
        server: '{{server}}'
        namespace: kube-state-metrics
      syncPolicy:
        syncOptions:
        - Replace=true
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
        retry:
          limit: 30
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s