apiVersion: v2
name: vpa
description: A Helm chart for Kubernetes Vertical Pod Autoscaler
type: application
version: 1.0.0
appVersion: 1.0.0
maintainers:
  - name: Sachin Agarwal
home: https://github.com/sam0787/demo-namespaces-as-a-service/helm-charts/vpa
sources:
  - https://github.com/sam0787/demo-namespaces-as-a-service/helm-charts/vpa
  - https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler
kubeVersion: ">= 1.24.0-0"
