{{- if eq .Values.ingress.enabled true }}

apiVersion: v1
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "pg-common.fullname" . }}
  namespace: {{ .Values.namespaceName }}
  labels:
    {{- include "pg-common.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          service:
            {{- if eq .Values.ingress.backendServiceOverride.enabled true }}
            name: {{ .Values.ingress.backendServiceOverride.name }}
            {{- else }}
            name: {{ include "pg-common.fullname" . }}
            {{- end }}
            port:
              {{- if eq .Values.ingress.backendServiceOverride.enabled true }}
              number: {{ .Values.ingress.backendServiceOverride.port }}
              {{- else }}
              number: {{ .Values.service.port }}
              {{- end }}
        pathType: ImplementationSpecific
{{- end }}
