{{- if eq .Values.pdb.enabled true }}

apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "pg-common.fullname" . }}
  namespace: {{ .Values.namespaceName }}
  labels:
    {{- include "pg-common.labels" . | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
    {{- include "pg-common.selectorLabels" . | nindent 6  }}
{{- end }}
