{{- if eq .Values.serviceMonitor.enabled true }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "pg-common.fullname" . }}
  namespace: {{ .Values.namespaceName }}
  labels:
    {{- include "pg-common.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: monitoring
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "pg-common.labels" . | nindent 6 }}
  endpoints:
  - port: {{ .Values.serviceMonitor.port }}
    path: {{ .Values.serviceMonitor.path }}
{{- end }}
